
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-19T14:24:04-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "4fe2731f4bad9ddf584731037df3d64a8696a2d5",
 "version": "5.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
