
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-26T15:07:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b02676dc73a26566310409067029f568965ca2de",
 "version": "0.1.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
