
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-19T10:17:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ddad5dafe6cb71c1a752a7a357536c4c8a0f55b8",
 "version": "0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
