# Configuration

site_name: Information Retrieval for Experimaestro
site_description: experimaestro-ir Information Retrieval module for Experimaestro
repo_url: https://github.com/bpiwowar/experimaestro-ir

# Main pages
nav:
  - Home: index.md
  - Learning to rank: letor.md
  - Neural models: neural.md
  - Misc: misc.md

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - admonition
  - pymdownx.snippets:
      base_path: .
  - toc:
      baselevel: 1

plugins:
  - datamaestro:
      repository: ir

  - experimaestro:
        init:
          # Allows to cope with uninstalled modules when generating documentation
          - xpmir.mkdocs_init
        modules:
          - letor.md: [xpmir.letor, xpmir.rankers]
          - neural.md: [xpmir.neural]
          - misc.md: [xpmir]
        external:
          - datamaestro_text: https://datamaestro-text.readthedocs.io/en/latest/experimaestro-mapping.json

# Theme
theme:
    name: readthedocs
    highlightjs: true
