[build-system]
requires = [
    "setuptools>=42",
    "markdown",
    "pygments"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    | __pycache__
    | dist
)/
'''