[executables]
lotus-miner = "/usr/local/bin/lotus-miner"
ansible = "/usr/local/bin/ansible"

[lotus]
miner_path = "/filecoin/lotusminer"

[ansible]
hosts = "/etc/ansible/hosts"

[pledge]
interval = "2m"