# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tecton_proto/online_store_writer/config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tecton_proto.canary import type_pb2 as tecton__proto_dot_canary_dot_type__pb2
from tecton_proto.common import id_pb2 as tecton__proto_dot_common_dot_id__pb2
from tecton_proto.data import feature_package_pb2 as tecton__proto_dot_data_dot_feature__package__pb2
from tecton_proto.data import feature_view_pb2 as tecton__proto_dot_data_dot_feature__view__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tecton_proto/online_store_writer/config.proto',
  package='tecton_proto.online_store_writer',
  syntax='proto2',
  serialized_options=b'\n\034com.tecton.onlinestorewriterP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-tecton_proto/online_store_writer/config.proto\x12 tecton_proto.online_store_writer\x1a\x1etecton_proto/canary/type.proto\x1a\x1ctecton_proto/common/id.proto\x1a\'tecton_proto/data/feature_package.proto\x1a$tecton_proto/data/feature_view.proto\"\x95\x03\n\x1eOnlineStoreWriterConfiguration\x12*\n\x11status_table_name\x18\x01 \x01(\tR\x0fstatusTableName\x12&\n\x0f\x64\x61ta_table_name\x18\x02 \x01(\tR\rdataTableName\x12*\n\x11\x63\x61nary_table_name\x18\x03 \x01(\tR\x0f\x63\x61naryTableName\x12@\n\x0b\x63\x61nary_type\x18\x04 \x01(\x0e\x32\x1f.tecton_proto.canary.CanaryTypeR\ncanaryType\x12\x1b\n\tcanary_id\x18\x05 \x01(\tR\x08\x63\x61naryId\x12\x38\n\x18\x63\x61nary_downsample_factor\x18\x06 \x01(\x05R\x16\x63\x61naryDownsampleFactor\x12T\n\x13online_store_params\x18\x08 \x01(\x0b\x32$.tecton_proto.data.OnlineStoreParamsR\x11onlineStoreParamsJ\x04\x08\x07\x10\x08\"\xfb\x02\n\x1eOnlineStoreCopierConfiguration\x12\x8b\x01\n!online_store_writer_configuration\x18\x01 \x01(\x0b\x32@.tecton_proto.online_store_writer.OnlineStoreWriterConfigurationR\x1eonlineStoreWriterConfiguration\x12\x41\n\x0c\x66\x65\x61ture_view\x18\x02 \x01(\x0b\x32\x1e.tecton_proto.data.FeatureViewR\x0b\x66\x65\x61tureView\x12\x16\n\x06\x62ucket\x18\x03 \x01(\tR\x06\x62ucket\x12\x10\n\x03key\x18\x04 \x01(\tR\x03key\x12^\n\x1fmaterialization_task_attempt_id\x18\x05 \x01(\x0b\x32\x17.tecton_proto.common.IdR\x1cmaterializationTaskAttemptIdB \n\x1c\x63om.tecton.onlinestorewriterP\x01'
  ,
  dependencies=[tecton__proto_dot_canary_dot_type__pb2.DESCRIPTOR,tecton__proto_dot_common_dot_id__pb2.DESCRIPTOR,tecton__proto_dot_data_dot_feature__package__pb2.DESCRIPTOR,tecton__proto_dot_data_dot_feature__view__pb2.DESCRIPTOR,])




_ONLINESTOREWRITERCONFIGURATION = _descriptor.Descriptor(
  name='OnlineStoreWriterConfiguration',
  full_name='tecton_proto.online_store_writer.OnlineStoreWriterConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_table_name', full_name='tecton_proto.online_store_writer.OnlineStoreWriterConfiguration.status_table_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='statusTableName', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_table_name', full_name='tecton_proto.online_store_writer.OnlineStoreWriterConfiguration.data_table_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='dataTableName', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='canary_table_name', full_name='tecton_proto.online_store_writer.OnlineStoreWriterConfiguration.canary_table_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='canaryTableName', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='canary_type', full_name='tecton_proto.online_store_writer.OnlineStoreWriterConfiguration.canary_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='canaryType', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='canary_id', full_name='tecton_proto.online_store_writer.OnlineStoreWriterConfiguration.canary_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='canaryId', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='canary_downsample_factor', full_name='tecton_proto.online_store_writer.OnlineStoreWriterConfiguration.canary_downsample_factor', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='canaryDownsampleFactor', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='online_store_params', full_name='tecton_proto.online_store_writer.OnlineStoreWriterConfiguration.online_store_params', index=6,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='onlineStoreParams', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=630,
)


_ONLINESTORECOPIERCONFIGURATION = _descriptor.Descriptor(
  name='OnlineStoreCopierConfiguration',
  full_name='tecton_proto.online_store_writer.OnlineStoreCopierConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='online_store_writer_configuration', full_name='tecton_proto.online_store_writer.OnlineStoreCopierConfiguration.online_store_writer_configuration', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='onlineStoreWriterConfiguration', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feature_view', full_name='tecton_proto.online_store_writer.OnlineStoreCopierConfiguration.feature_view', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='featureView', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bucket', full_name='tecton_proto.online_store_writer.OnlineStoreCopierConfiguration.bucket', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='bucket', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='tecton_proto.online_store_writer.OnlineStoreCopierConfiguration.key', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='key', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='materialization_task_attempt_id', full_name='tecton_proto.online_store_writer.OnlineStoreCopierConfiguration.materialization_task_attempt_id', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='materializationTaskAttemptId', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=633,
  serialized_end=1012,
)

_ONLINESTOREWRITERCONFIGURATION.fields_by_name['canary_type'].enum_type = tecton__proto_dot_canary_dot_type__pb2._CANARYTYPE
_ONLINESTOREWRITERCONFIGURATION.fields_by_name['online_store_params'].message_type = tecton__proto_dot_data_dot_feature__package__pb2._ONLINESTOREPARAMS
_ONLINESTORECOPIERCONFIGURATION.fields_by_name['online_store_writer_configuration'].message_type = _ONLINESTOREWRITERCONFIGURATION
_ONLINESTORECOPIERCONFIGURATION.fields_by_name['feature_view'].message_type = tecton__proto_dot_data_dot_feature__view__pb2._FEATUREVIEW
_ONLINESTORECOPIERCONFIGURATION.fields_by_name['materialization_task_attempt_id'].message_type = tecton__proto_dot_common_dot_id__pb2._ID
DESCRIPTOR.message_types_by_name['OnlineStoreWriterConfiguration'] = _ONLINESTOREWRITERCONFIGURATION
DESCRIPTOR.message_types_by_name['OnlineStoreCopierConfiguration'] = _ONLINESTORECOPIERCONFIGURATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OnlineStoreWriterConfiguration = _reflection.GeneratedProtocolMessageType('OnlineStoreWriterConfiguration', (_message.Message,), {
  'DESCRIPTOR' : _ONLINESTOREWRITERCONFIGURATION,
  '__module__' : 'tecton_proto.online_store_writer.config_pb2'
  # @@protoc_insertion_point(class_scope:tecton_proto.online_store_writer.OnlineStoreWriterConfiguration)
  })
_sym_db.RegisterMessage(OnlineStoreWriterConfiguration)

OnlineStoreCopierConfiguration = _reflection.GeneratedProtocolMessageType('OnlineStoreCopierConfiguration', (_message.Message,), {
  'DESCRIPTOR' : _ONLINESTORECOPIERCONFIGURATION,
  '__module__' : 'tecton_proto.online_store_writer.config_pb2'
  # @@protoc_insertion_point(class_scope:tecton_proto.online_store_writer.OnlineStoreCopierConfiguration)
  })
_sym_db.RegisterMessage(OnlineStoreCopierConfiguration)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
