[tool.poetry]
name = "django-lc-utils"
version = "0.2.0"
description = "Utilities for Django application"
authors = ["Tejas Bhandari <tejas@thesummitgrp.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.1.13"
django-model-utils = "^4.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
