
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-18T23:43:57+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "15470a312df4f4a88de39391e9eb6e5bb387a0dd",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
