[build-system]
requires = [
    "setuptools>=58.2.0",
    "wheel>=0.37.0",
    "pip>=21.3",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = [
    "py36",
    "py37",
    "py38",
]
