
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-25T12:35:05-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ce7bdae639f762fc741d281eda3d3cbcb6dd7f3",
 "version": "1.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
