info = {"message": "Update DM from master commit", "commit": "095f4bf52cf0d86616357394892e872f7c9b0d55", "date": "2021-11-18 23:42:49 +0300", "branch": "release/1.4", "version": "1.3.0+179.g095f4bf5.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
