[tool.poetry]
name = "kuay"
version = "0.1.17"
description = ""
authors = ["jhnnsrs <jhnnsrs@gmail.com>"]
packages = [{include = "kuay"}]

[tool.poetry.dependencies]
python = "^3.8"
herre = "^0.1.53"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-aiohttp = "^0.3.0"
tox = "^3.24.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"