# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: simbench

on:
  push:
    branches: '*'
    paths-ignore:
      - 'CHANGELOG.rst'
  pull_request:
    branches: '*'
    paths-ignore:
      - 'CHANGELOG.rst'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    #- uses: julia-actions/setup-julia@v1.5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if ${{ matrix.python-version == '3.7' }}; then python -m pip install pypower; fi
        if ${{ matrix.python-version == '3.6' || matrix.python-version == '3.7' || matrix.python-version == '3.8' || matrix.python-version == '3.9' }}; then python -m pip install matplotlib; fi
        pip install .["all"]
    - name: List of installed packages
      run: |
        pip list
    - name: Test with pytest
      if: ${{ matrix.python-version != '3.8' }}
      run: |
        pytest
    - name: Test with pytest and Codecov
      if: ${{ matrix.python-version == '3.8' }}
      run: |
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      if: ${{ matrix.python-version == '3.8' }}
      uses: codecov/codecov-action@v1
      with:
        verbose: true
