[[bench]]
harness = false
name = "benchmark"
path = "benches/lib.rs"

[dependencies]
conv = "^0.3.3"
dyn-clonable = "^0.9.0"
emcee = "^0.3.0"
enum_dispatch = "^0.3.7"
itertools = "^0.10.0"
lazy_static = "^1.4.0"
libm = "~0.2.1"
light-curve-common = "0.1.0"
macro_const = "0.1.0"
ndarray = "^0.15.3"
ndarray-stats = "^0.5"
num-complex = "^0.3"
num-traits = "^0.2"
schemars = "^0.8.3"
thiserror = "^1.0"
thread_local = "^1.1"
unzip3 = "^1.0"

[dependencies.GSL]
default-features = false
optional = true
version = "~6.0.0"

[dependencies.emcee_rand]
package = "rand"
version = "^0.3.15"

[dependencies.fftw]
default-features = false
version = "0.7.0"

[dependencies.serde]
features = ["derive"]
version = "^1.0"

[dev-dependencies]
approx = "^0.5"
chfft = "^0.3.4"
clap = "3.0.0-beta.5"
criterion = "^0.3"
hyperdual = "^0.5.0"
plotters-bitmap = "^0.3.1"
rand = "^0.7"
rand_distr = "^0.2"
rayon = "~1.5.1"
realfft = "^1.1"
rustfft = "^5.0"
serde_json = "^1.0"
serde_test = "^1.0"
serde_type_name = "0.2.0"

[dev-dependencies.light-curve-feature]
default-features = false
features = ["gsl"]
path = "../light-curve-feature"

[dev-dependencies.light-curve-feature-test-util]
path = "../light-curve-feature-test-util"

[dev-dependencies.plotters]
default-features = false
features = ["errorbar", "line_series", "ttf"]
version = "^0.3.1"

[features]
default = ["fftw-source"]
fftw-mkl = ["fftw/intel-mkl"]
fftw-source = ["fftw/source"]
fftw-system = ["fftw/system"]
gsl = ["GSL/v2_1"]

[lib]
bench = false

[package]
authors = ["Konstantin Malanchev <hombit@gmail.com>"]
description = "Feature extractor from noisy time series"
edition = "2018"
license = "GPL-3.0-or-later"
name = "light-curve-feature"
readme = "README.md"
repository = "https://github.com/light-curve/light-curve"
version = "0.3.3"
[package.metadata.docs.rs]
features = ["fftw-system", "gsl"]
no-default-features = true
rustdoc-args = ["--html-in-header", "katex-header.html"]
