[tool.poetry]
name = "context-handler"
version = "2.1.0"
description = ""
authors = ["Gustavo Correa <self.gustavocorrea@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
typing-extensions = "^3.10.0"
fastapi = {version = "^0.70.0", optional = true}
sanic = {version = "^21.9.1", optional = true}

[tool.poetry.dev-dependencies]
black = "^21.9b0"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-asyncio = "^0.16.0"
autoflake = "^1.4"
isort = "^5.9.3"
pylint = "^2.11.1"
bandit = "^1.7.0"

[tool.poetry.extras]
fastapi = ["fastapi"]
sanic = ["sanic"]

[tool.black]
line_length = 79

[tool.isort]
profile = "black"

[tool.commitizen]
name = "cz_conventional_commits"
version = "2.1.0"
tag_format = "$version"
annotated_tag = true
version_files = [
    "pyproject.toml:version",
    "context_handler/__init__.py"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
