
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-23T13:14:29-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "be067bcf560103e2d2f2043fce8a5ea244ef6f53",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
