
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-22T15:55:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d8693643ac46ca491a94643376004b44dcc0ccef",
 "version": "1.15.0.post.dev572"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
