[tool.poetry]
name = "phobos"
version = "v1.1.12"
description = "Training utility library and config manager for Granular Machine Vision research"
authors = ["Sagar Verma <sagar@granular.ai>", "Siddharth Gupta <sid@granular.ai>"]
license = "MIT"
readme = "README.rst"
classifiers = [
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
]
repository='https://github.com/granularai/phobos'

[tool.poetry.scripts]
phobos = 'phobos.cli:cli'

[tool.poetry.dependencies]
python = "^3.7.0"
torch = "1.9.0"
polyaxon = "^1.10.1"
polyaxon-sdk = "^1.10.1"
MedPy = "^0.4.0"
numpy = "^1.21.0"
sphinx-rtd-theme = "^0.5.2"
torchvision = "0.10.0"
pytorch-lightning = "^1.3.8"
scikit-learn = "^0.24.2"
albumentations = "^1.0.3"
numpydoc = "^1.1.0"
sphinx-issues = "^1.2.0"
sphinx-prompt = "^1.4.0"
rasterio = "^1.2.6"
webdataset = "^0.1.62"
cookiecutter = "^1.7.3"
pycocotools = "^2.0.2"
yacs = "^0.1.8"

[tool.poetry.dev-dependencies]
pip = "^21.1.3"
bump2version = "^1.0.1"
watchdog = "^2.1.3"
flake8 = "^3.9.2"
tox = "^3.24.0"
coverage = "^5.5"
Sphinx = "^4.1.1"
twine = "^3.4.1"
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
