name: shut
version: 0.21.1
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
license: MIT
url: https://github.com/NiklasRosenstein/shut
description: Automates the heavy lifting of release and distribution management for
  pure Python packages.
typed: true
requirements:
- python ^3.7
- beautifulsoup4 ^4.8.1
- databind.core ^1.1.2
- databind.json ^1.1.2
- click >=7.1,<9.0
- networkx ^2.4
- nr.fs ^1.5.0
- nr.parsing.date ^1.0.3
- nr.proxy ^1.0.0
- nr.pylang.utils ^0.0.1
- nr.utils.git ~0.1.3
- nr.stream ^0.2.2
- requests ^2.22.0
- packaging ^20.1
- PyYAML ^5.1.0
- termcolor ^1.1.0
- typing-extensions ^3.10.0.0
- twine
- wheel
- Mako ^1.1.5
test-requirements:
- pytest
- mypy
- types-beautifulsoup4
- types-click
- types-requests
- types-PyYAML
- types-setuptools
- types-termcolor
entrypoints:
  console_scripts:
  - shut = shut.commands:shut
  shut.test_drivers:
  - mypy = shut.test.mypy:MypyTestDriver
  - pylint = shut.test.pylint:PylintTestDriver
  - pytest = shut.test.pytest:PytestDriver
  shut.templates:
  - github-actions = shut.templates.github_actions:GithubActionsTemplate
  - pylintrc = shut.templates.pylintrc:PylintRcTemplate
package-data:
- include: data/license_templates/*.txt
- include: data/templates/*
test-drivers:
- type: mypy
- type: pytest
- type: pylint
  args: [ '--fail-under=8.0' ]
publish:
  pypi:
    credentials:
      username: __token__
      password: '$PYPI_TOKEN'
      test_username: __token__
      test_password: '$TESTPYPI_TOKEN'
templates:
- type: github-actions
  pypi-publish: true
- type: pylintrc
  use: shut
