
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-23T09:29:47-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "177b1e18cfaf225c637272ed44c44306cbe98cd7",
 "version": "4.9.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
