
[tool.poetry]
name = "ree-connector"
version = "0.1.1-alpha.2"
description = "Lightweight package to consume data from REE (Red Eléctrica de España) API"
authors = ["Jorge Marín <jormarcor@alum.us.es>"]
license = "MIT"
readme = "README.md"
homepage = ""
repository = ""
documentation = ""
keywords = [
    "Python",
    "Packages",
    "Energy",
    "Tools",
    "Electricity Markets",
    "IoT",
    "Domotics"
]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
