[tool.poetry]
name = "md410_2022_conv_common"
version = "1.17.0"
description = "Common libraries for applications related to the 2022 Lions MD410 Convention"
authors = ["Kim van Wyk <vanwykk@gmail.com>"]
repository = "https://gitlab.com/md410_2022_conv/md410_2022_conv_common"
readme = "readme.md" 

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.8.2"
boto3 = "^1.20.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
