# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SDMS_Anon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SDMS_pb2 as SDMS__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SDMS_Anon.proto',
  package='SDMS.Anon',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0fSDMS_Anon.proto\x12\tSDMS.Anon\x1a\nSDMS.proto\"\n\n\x08\x41\x63kReply\"?\n\tNackReply\x12!\n\x08\x65rr_code\x18\x01 \x02(\x0e\x32\x0f.SDMS.ErrorCode\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\t\"\x10\n\x0eVersionRequest\"\x81\x01\n\x0cVersionReply\x12\r\n\x05major\x18\x01 \x02(\r\x12\x12\n\nmapi_major\x18\x02 \x02(\r\x12\x12\n\nmapi_minor\x18\x03 \x02(\r\x12\x0c\n\x04\x63ore\x18\x04 \x02(\r\x12\x0b\n\x03web\x18\x05 \x02(\r\x12\x0c\n\x04repo\x18\x06 \x02(\r\x12\x11\n\tclient_py\x18\x07 \x02(\r\"\x16\n\x14GetAuthStatusRequest\">\n\x1d\x41uthenticateByPasswordRequest\x12\x0b\n\x03uid\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"+\n\x1a\x41uthenticateByTokenRequest\x12\r\n\x05token\x18\x01 \x02(\t\",\n\x0f\x41uthStatusReply\x12\x0c\n\x04\x61uth\x18\x01 \x02(\x08\x12\x0b\n\x03uid\x18\x02 \x01(\t*\x12\n\x08Protocol\x12\x06\n\x02ID\x10\x01')
  ,
  dependencies=[SDMS__pb2.DESCRIPTOR,])

_PROTOCOL = _descriptor.EnumDescriptor(
  name='Protocol',
  full_name='SDMS.Anon.Protocol',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=448,
  serialized_end=466,
)
_sym_db.RegisterEnumDescriptor(_PROTOCOL)

Protocol = enum_type_wrapper.EnumTypeWrapper(_PROTOCOL)
ID = 1



_ACKREPLY = _descriptor.Descriptor(
  name='AckReply',
  full_name='SDMS.Anon.AckReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=52,
)


_NACKREPLY = _descriptor.Descriptor(
  name='NackReply',
  full_name='SDMS.Anon.NackReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='SDMS.Anon.NackReply.err_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='SDMS.Anon.NackReply.err_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=117,
)


_VERSIONREQUEST = _descriptor.Descriptor(
  name='VersionRequest',
  full_name='SDMS.Anon.VersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=135,
)


_VERSIONREPLY = _descriptor.Descriptor(
  name='VersionReply',
  full_name='SDMS.Anon.VersionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major', full_name='SDMS.Anon.VersionReply.major', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mapi_major', full_name='SDMS.Anon.VersionReply.mapi_major', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mapi_minor', full_name='SDMS.Anon.VersionReply.mapi_minor', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='core', full_name='SDMS.Anon.VersionReply.core', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='web', full_name='SDMS.Anon.VersionReply.web', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repo', full_name='SDMS.Anon.VersionReply.repo', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_py', full_name='SDMS.Anon.VersionReply.client_py', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=267,
)


_GETAUTHSTATUSREQUEST = _descriptor.Descriptor(
  name='GetAuthStatusRequest',
  full_name='SDMS.Anon.GetAuthStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=291,
)


_AUTHENTICATEBYPASSWORDREQUEST = _descriptor.Descriptor(
  name='AuthenticateByPasswordRequest',
  full_name='SDMS.Anon.AuthenticateByPasswordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='SDMS.Anon.AuthenticateByPasswordRequest.uid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='SDMS.Anon.AuthenticateByPasswordRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=355,
)


_AUTHENTICATEBYTOKENREQUEST = _descriptor.Descriptor(
  name='AuthenticateByTokenRequest',
  full_name='SDMS.Anon.AuthenticateByTokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='SDMS.Anon.AuthenticateByTokenRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=400,
)


_AUTHSTATUSREPLY = _descriptor.Descriptor(
  name='AuthStatusReply',
  full_name='SDMS.Anon.AuthStatusReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auth', full_name='SDMS.Anon.AuthStatusReply.auth', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='SDMS.Anon.AuthStatusReply.uid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=446,
)

_NACKREPLY.fields_by_name['err_code'].enum_type = SDMS__pb2._ERRORCODE
DESCRIPTOR.message_types_by_name['AckReply'] = _ACKREPLY
DESCRIPTOR.message_types_by_name['NackReply'] = _NACKREPLY
DESCRIPTOR.message_types_by_name['VersionRequest'] = _VERSIONREQUEST
DESCRIPTOR.message_types_by_name['VersionReply'] = _VERSIONREPLY
DESCRIPTOR.message_types_by_name['GetAuthStatusRequest'] = _GETAUTHSTATUSREQUEST
DESCRIPTOR.message_types_by_name['AuthenticateByPasswordRequest'] = _AUTHENTICATEBYPASSWORDREQUEST
DESCRIPTOR.message_types_by_name['AuthenticateByTokenRequest'] = _AUTHENTICATEBYTOKENREQUEST
DESCRIPTOR.message_types_by_name['AuthStatusReply'] = _AUTHSTATUSREPLY
DESCRIPTOR.enum_types_by_name['Protocol'] = _PROTOCOL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AckReply = _reflection.GeneratedProtocolMessageType('AckReply', (_message.Message,), dict(
  DESCRIPTOR = _ACKREPLY,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.AckReply)
  ))
_sym_db.RegisterMessage(AckReply)

NackReply = _reflection.GeneratedProtocolMessageType('NackReply', (_message.Message,), dict(
  DESCRIPTOR = _NACKREPLY,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.NackReply)
  ))
_sym_db.RegisterMessage(NackReply)

VersionRequest = _reflection.GeneratedProtocolMessageType('VersionRequest', (_message.Message,), dict(
  DESCRIPTOR = _VERSIONREQUEST,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.VersionRequest)
  ))
_sym_db.RegisterMessage(VersionRequest)

VersionReply = _reflection.GeneratedProtocolMessageType('VersionReply', (_message.Message,), dict(
  DESCRIPTOR = _VERSIONREPLY,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.VersionReply)
  ))
_sym_db.RegisterMessage(VersionReply)

GetAuthStatusRequest = _reflection.GeneratedProtocolMessageType('GetAuthStatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETAUTHSTATUSREQUEST,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.GetAuthStatusRequest)
  ))
_sym_db.RegisterMessage(GetAuthStatusRequest)

AuthenticateByPasswordRequest = _reflection.GeneratedProtocolMessageType('AuthenticateByPasswordRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATEBYPASSWORDREQUEST,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.AuthenticateByPasswordRequest)
  ))
_sym_db.RegisterMessage(AuthenticateByPasswordRequest)

AuthenticateByTokenRequest = _reflection.GeneratedProtocolMessageType('AuthenticateByTokenRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATEBYTOKENREQUEST,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.AuthenticateByTokenRequest)
  ))
_sym_db.RegisterMessage(AuthenticateByTokenRequest)

AuthStatusReply = _reflection.GeneratedProtocolMessageType('AuthStatusReply', (_message.Message,), dict(
  DESCRIPTOR = _AUTHSTATUSREPLY,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.AuthStatusReply)
  ))
_sym_db.RegisterMessage(AuthStatusReply)


# @@protoc_insertion_point(module_scope)

_msg_name_to_type = {
    'AckReply' : 256,
    'NackReply' : 257,
    'VersionRequest' : 258,
    'VersionReply' : 259,
    'GetAuthStatusRequest' : 260,
    'AuthenticateByPasswordRequest' : 261,
    'AuthenticateByTokenRequest' : 262,
    'AuthStatusReply' : 263
}

_msg_type_to_name = {
    256 : 'AckReply',
    257 : 'NackReply',
    258 : 'VersionRequest',
    259 : 'VersionReply',
    260 : 'GetAuthStatusRequest',
    261 : 'AuthenticateByPasswordRequest',
    262 : 'AuthenticateByTokenRequest',
    263 : 'AuthStatusReply'
}

_msg_name_to_type = {
    'AckReply' : 256,
    'NackReply' : 257,
    'VersionRequest' : 258,
    'VersionReply' : 259,
    'GetAuthStatusRequest' : 260,
    'AuthenticateByPasswordRequest' : 261,
    'AuthenticateByTokenRequest' : 262,
    'AuthStatusReply' : 263
}

_msg_type_to_name = {
    256 : 'AckReply',
    257 : 'NackReply',
    258 : 'VersionRequest',
    259 : 'VersionReply',
    260 : 'GetAuthStatusRequest',
    261 : 'AuthenticateByPasswordRequest',
    262 : 'AuthenticateByTokenRequest',
    263 : 'AuthStatusReply'
}

_msg_name_to_type = {
    'AckReply' : 256,
    'NackReply' : 257,
    'VersionRequest' : 258,
    'VersionReply' : 259,
    'GetAuthStatusRequest' : 260,
    'AuthenticateByPasswordRequest' : 261,
    'AuthenticateByTokenRequest' : 262,
    'AuthStatusReply' : 263
}

_msg_type_to_name = {
    256 : 'AckReply',
    257 : 'NackReply',
    258 : 'VersionRequest',
    259 : 'VersionReply',
    260 : 'GetAuthStatusRequest',
    261 : 'AuthenticateByPasswordRequest',
    262 : 'AuthenticateByTokenRequest',
    263 : 'AuthStatusReply'
}
