# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Version.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Version.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rVersion.proto*\x80\x01\n\x07Version\x12\r\n\tVER_MAJOR\x10\x01\x12\x12\n\x0eVER_MAPI_MAJOR\x10\x04\x12\x12\n\x0eVER_MAPI_MINOR\x10\x00\x12\x0c\n\x08VER_CORE\x10\x00\x12\x0b\n\x07VER_WEB\x10\x00\x12\x0c\n\x08VER_REPO\x10\x00\x12\x11\n\rVER_CLIENT_PY\x10\x00\x1a\x02\x10\x01')
)

_VERSION = _descriptor.EnumDescriptor(
  name='Version',
  full_name='Version',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VER_MAJOR', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VER_MAPI_MAJOR', index=1, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VER_MAPI_MINOR', index=2, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VER_CORE', index=3, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VER_WEB', index=4, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VER_REPO', index=5, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VER_CLIENT_PY', index=6, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=_b('\020\001'),
  serialized_start=18,
  serialized_end=146,
)
_sym_db.RegisterEnumDescriptor(_VERSION)

Version = enum_type_wrapper.EnumTypeWrapper(_VERSION)
VER_MAJOR = 1
VER_MAPI_MAJOR = 4
VER_MAPI_MINOR = 0
VER_CORE = 0
VER_WEB = 0
VER_REPO = 0
VER_CLIENT_PY = 0


DESCRIPTOR.enum_types_by_name['Version'] = _VERSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_VERSION._options = None
# @@protoc_insertion_point(module_scope)
