
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-21T10:38:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d779ebe2e144f5b9c5836c381bf113954a1ee4f",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
