[tool.poetry]
name = "Flunt"
version = "0.2.0"
description = "Python implementation of Domain Notification Pattern based in Flunt (.NET) developed by @andrebaltieri"
authors = ["Emerson Delatorre <38289677+Delatorrea@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
isort = "^5.10.1"
black = "^21.11b1"
pydocstyle = "^6.1.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
