
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-18T14:12:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ffdb6c8a22ba8185d562541d4038ec26016afff3",
 "version": "0.4.98"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
