[tool.poetry]
name = "codegrade"
version = "15.1.0"
description = "A client library for accessing CodeGrade"
license = "AGPL-3.0-only OR BSD-3-Clause-Clear"

authors = []

readme = "README.md"
packages = [
    {include = "codegrade"},
    {include = "cg_maybe"},
    {include = "cg_dt_utils"},
    {include = "cg_request_args"},
]
include = ["CHANGELOG.md", "LICENSES", "py.typed"]


[tool.poetry.dependencies]
python = ">=3.6.1,<4.0"
httpx = ">=0.19.0, <1.0.0"
dataclasses = {version="^0.8", python="~3.6"}
structlog = "^20.1.0"
validate-email = "^1.3"
python-dateutil = "^2.8.1"
typing-extensions = "^3.7.4.3"

[tool.poetry.dev-dependencies]
mypy = "==0.790.0"
Sphinx = "^4.2.0"
sphinx-autodoc-typehints = "^1.12.0"
m2r2 = "^0.3.1"
furo = "^2021.10.9"

[tool.black]
line-length = 79
target_version = ['py36']
experimental_string_processing = true
exclude = '''
(
  /(
    | \.git
    | \.venv
    | \.mypy_cache
  )/
)
'''

[tool.isort]
line_length = 80
multi_line_output = 3
include_trailing_comma = true

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}