[tool.pytest.ini_options]
addopts = "--doctest-modules -x"
usefixtures = "setup_tests"
norecursedirs = [
    "tested_project",
    "content",
    "dist",
    "build",
]

[tool.black]
line-length = 110