
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-25T13:58:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c1e127f0bbc6d7867b695dd6834b0cb5a7abb629",
 "version": "v1.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
