callbacks:
  - _target_: "classy.pl_callbacks.prediction.PredictionPLCallback"
    validation_path: null
    prediction_confs:
      - name: "validation"
        path: null  # if you leave it to None, it will be set to the validation path
        token_batch_size: 300
        limit: -1
        enabled_prediction_callbacks:
          - "file_dumper"
          - "seqeval"
    prediction_callbacks:
      file_dumper:
        _target_: "classy.pl_callbacks.prediction.FileDumperPredictionCallback"
      seqeval:
        _target_: "classy.pl_callbacks.prediction.SeqEvalPredictionCallback"
    prediction_dataset_conf: ${prediction.dataset}