callbacks:
  - _target_: "classy.pl_callbacks.prediction.PredictionPLCallback"
    validation_path: null
    prediction_confs:
      - name: "validation"
        path: null  # if you leave it to None, it will be set to the validation path
        token_batch_size: 800
        limit: 1000
        enabled_prediction_callbacks:
          - "file_dumper"
          - "sacrebleu"
    prediction_callbacks:
      file_dumper:
        _target_: "classy.pl_callbacks.prediction.FileDumperPredictionCallback"
      sacrebleu:
        _target_: "classy.pl_callbacks.prediction.SQuADV1Callback"
    prediction_dataset_conf: ${prediction.dataset}