# coding: utf-8

"""
    Nomad Pilot

    This is the API descriptor for the Nomad Pilot API, responsible for shipping and logistics processing. Developed by [Samarkand Global](https://www.samarkand.global/) in partnership with [SF Express](https://www.sf-express.com/), [eSinotrans](http://air.esinotrans.com/), [sto](http://sto-express.co.uk/). Read the documentation online at [Nomad API Suite](https://api.samarkand.io/). - Install for node with `npm install nomad_pilot_cli` - Install for python with `pip install nomad-pilot-cli` - Install for Maven users `groupId, com.gitlab.samarkand-nomad; artifactId, nomad-pilot-cli`  # noqa: E501

    The version of the OpenAPI document: 1.44.1
    Contact: paul@samarkand.global
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import nomad_pilot_cli
from nomad_pilot_cli.models.api_response_locker_item import ApiResponseLockerItem  # noqa: E501
from nomad_pilot_cli.rest import ApiException

class TestApiResponseLockerItem(unittest.TestCase):
    """ApiResponseLockerItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiResponseLockerItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = nomad_pilot_cli.models.api_response_locker_item.ApiResponseLockerItem()  # noqa: E501
        if include_optional :
            return ApiResponseLockerItem(
                belong_org = 56, 
                big_cell_count_left = 56, 
                cabinet_code = 'FC75522956', 
                can_pay_prefix = True, 
                city = '深圳市', 
                city_code = '755', 
                distance = 56, 
                district = '0', 
                latitude = '755', 
                longitude = '0', 
                middle_cell_count_left = 56, 
                province = '0', 
                small_cell_count_left = 56, 
                throw_address = '0', 
                throw_building_location = '0', 
                whole_throwaddress = '0'
            )
        else :
            return ApiResponseLockerItem(
        )

    def testApiResponseLockerItem(self):
        """Test ApiResponseLockerItem"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
