image: python:3.8

definitions:
  steps:
    - step: &lint
        caches:
          - pip
        name: Lint
        script:
          - pip install pre-commit
          - pre-commit install
          - pre-commit run --all-files
    - step: &test
        name: Test
        script:
          - pip install tox
          - tox -e py38
    - step: &scan
        caches:
          - pip
        name: Scan
        script:
          - pip install .
          - pip install safety
          - safety check --full-report ${SAFETY_IGNORE}
    - step: &publish
        name: Publish
        script:
          - pip install -U pip
          - pip install twine pep517
          - python -m pep517.build --binary --source --out-dir wheelhouse .
          - python -m twine upload --skip-existing wheelhouse/*

pipelines:
  default:
    - step: *lint
    - step: *test
    - step: *scan
  tags:
    'v*':
      - step: *lint
      - step: *test
      - step: *scan
      - step: *publish
