[tool.poetry]
name = "vanoma-api-utils"
version = "0.1.0"
description = "Python utils for vanoma APIs"
authors = ["Vanoma <contact@vanoma.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
Django = "^3.2.9"
djangorestframework = "^3.12.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
