
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-16T09:26:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "993b17c7ec12e94e2bb6b88bcd9da9d420caee45",
 "version": "v0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
