
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-23T23:47:01-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "2949d612b92ed46fc4b7d1b4c0e884f52c7b9e06",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
