[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lotide_luna"
authors = [{name = "Ngô Ngọc Đức Huy", email = "huyngo@disroot.org"}]
readme = "README.md"
classifiers = [
  'Development Status :: 2 - Pre-Alpha',
  'Environment :: Web Environment',
  'Framework :: Django',
  'Operating System :: OS Independent',
  'Programming Language :: Python',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3 :: Only',
  'Programming Language :: Python :: 3.6',
  'Programming Language :: Python :: 3.7',
  'Programming Language :: Python :: 3.8',
  'Programming Language :: Python :: 3.9',
  'License :: OSI Approved :: GNU Affero General Public License v3',
  'Topic :: Communications'
]
dynamic = ["version", "description"]
requires-python = ">=3.6"
dependencies = [
  'django',
  'requests',
]

[project.urls]
Home = "https://sr.ht/~huyngo/luna"
