[tool.poetry]
name = "locli"
version = "0.3.9"
description = ""
authors = ["wonjae.h <warren@telelian.com>"]

[tool.poetry.dependencies]
python = "^3.6"
redis = "^4.0.1"
loguru = "^0.5.3"
hiredis = "^2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
commitizen = "^1.22.0"

[tool.poetry.scripts]
exam1 = "examples.exam1:main"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.3.9"
tag_format = "$version"
version_files = [
    "locli/__init__.py",
    "pyproject.toml:version"
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
