
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-26T15:48:59-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3f686f70a5e3f0fbb84158d129958f00925da55",
 "version": "2.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
