#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='pyshs',
      version='0.1.13',
      description='Module PySHS - Faciliter le traitement statistique en SHS',
      author='Emilien Schultz',
      author_email='emilien.schultz@gmail.com',
      url='http://pyshs.fr',
      py_modules=['pyshs'],
     )
