language: python

python:
  - '3.5'
  - '3.6'

os:
  - linux

addons:
  apt:
    packages:
    - libudev-dev

cache: pip

install:
  - python -m pip install --upgrade pip setuptools

script:
  - python setup.py build

notifications:
  email: false
