#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['noteout', 'noteout.tests']

package_data = \
{'': ['*'], 'noteout.tests': ['qbook/*']}

install_requires = \
['panflute', 'jupytext']

entry_points = \
{'console_scripts': ['noteout-filter-divspans = noteout.filter_divspans:main',
                     'noteout-filter-nb-only = noteout.nb_only:main',
                     'noteout-filter-pre = noteout.filter_pre:main',
                     'noteout-write-doc = noteout.write_doc:main',
                     'noteout-write-meta = noteout.write_meta:main',
                     'noteout-write-notebooks = noteout.write_notebooks:main']}

setup(name='noteout',
      version='0.0.3a7',
      description='Notebook parsing filters for Pandoc',
      author='Matthew Brett',
      author_email='matthew.brett@gmail.com',
      url='https://github.com/matthew-brett/noteout',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
