[tool.poetry]
name = "supplr"
version = "0.1.1"
description = "supplr CLI application for management Marathon board"
authors = ["GreenLab <greenlab@jinr.ru>"]
license = "Apache License, Version 2.0"

[tool.poetry.dependencies]
python = "^3.6"
click = ">=8.0.1"
pandas = ">=1.3.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
supplr = 'supplr.main:cli'
