[tool.poetry]
name = "tmprc"
version = "0.1.2"
description = ""
authors = ["subbarayudu <subbarayudu@micropyramid.com>"]
keywords = ["runcode"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/runcode-io/runcode-python"
repository = "https://github.com/runcode-io/runcode-python"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
