[tool.poetry]
name = "temprc"
version = "0.1.0"
description = ""
authors = ["subbarayudu <subbarayudu@micropyramid.com>"]
keywords = ["vscode", "poetry"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/"
repository = "https://github.com/"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.6"
poetry = "^1.1.11"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
temprc = 'temprc:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
