parameters:
  databricksbundle:
    databricks_connect:
      connection:
        address: 'https://westeurope.azuredatabricks.net'
        token: 'abcd123456'
        cluster_id: '0416-084917-doles835'
        org_id: 123456789

    storages:
      dev:
        type: testing
        tenant_id: "123456"
        storage_name: "aaa"
        secret_scope: some_scope1
        secret_key: some_key1
      prod:
        type: testing
        tenant_id: "987654"
        storage_name: "bbb"
        secret_scope: some_scope2
        secret_key: some_key2

services:
  databricksbundle.storage.testing.TestingConfigurator:
    tags:
      - 'databricks.storage.configurator'
