# Generated by Django 3.2.6 on 2021-11-24 18:05

import balloon_block_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200911_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='content2',
            field=balloon_block_editor.fields.BalloonBlockEditorField(default='test'),
            preserve_default=False,
        ),
    ]
