[tool.poetry]
name = "ipfabric"
version = "0.0.1"
description = "Python package for interacting with IP Fabric"
authors = [
    "Justin Jeffery <justin.jeffery@ipfabric.io>",
    "Community Fabric <communityfabric@ipfabric.io>"]
license = "MIT"
readme = "README.md"
homepage = ""
repository = ""
keywords = ["ipfabric", "ip-fabric", "community-fabric"]

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.21.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
