
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-24T20:02:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ba15a9fd4c1345331d10f19e552c81cac453ee5f",
 "version": "1.15.0.post.dev592"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
