[tool.poetry]
name = "biterator"
version = "0.4.0"
description = "Bit manipulation and iteration tool suite."
authors = ["derek-strasters <paracite.org@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "3.8.10"

[tool.poetry.dev-dependencies]
pre-commit = "*"
black = "*"
pydocstyle = "*"
pytest = "*"
mypy = "*"
coverage = "*"
isort = "*"

flake8 = "*"
flake8-black = "*"
flake8-coding = "*"
flake8-commas = "*"
flake8-isort = "*"
flake8-import-order = "*"
flake8-quotes = "*"
flake9 = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target_version = ["py38"]
line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.flake8]
statistics = true
inline-quotes = "double"
multiline-quotes = "double"
no-accept-encodings = true
import-order-style = "pep8"
exclude = "venv, dist"
max-line-length = 120
extend-ignore = "E203" # See https://github.com/PyCQA/pycodestyle/issues/373

[tool.pytest.ini_options]
addopts = "--doctest-modules"

[tool.pydocstyle]
match-dir = "(?!venv|dist).*"
