
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-24T03:08:14-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b0b5c4aaad4abb67a6b4d6cb58e8a2fcc6caada",
 "version": "0.3.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
