[tool.poetry]
name = "mactidy"
version = "0.1.0"
description = ""
authors = ["NhimHB <chienvq@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.3.4"
Send2Trash = "^1.8.0"
configparser = "^5.1.0"

[tool.poetry.dev-dependencies]
black = "^21.10b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
