
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-19T09:57:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "97c8242e149d5992414e5e2e3d2348a5881c1581",
 "version": "0.10.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
