DEFAULT_TRANSITION = 1

EXT_XDIMMER = "xdimmer"
EXT_X8R = "x8r"
EXT_XTHL = "xthl"
EXT_X4FP = "x4fp"
EXT_X8D = "x8d"
EXT_X24D = "x24d"
EXT_X4VR = "x4vr"
EXT_X010V = "x010v"
EXT_X200 = "x200"
EXT_X400 = "x400"
EXT_XDISPLAY = "xdisplay"
EXT_XPWM = "xpwm"

EXTENSIONS = [
    EXT_XTHL, EXT_X4FP, EXT_X24D, EXT_X4VR, EXT_XDIMMER, EXT_X8R,
    EXT_X010V, EXT_X200, EXT_X400, EXT_XDISPLAY, EXT_XPWM
]

VALUE_ON = "on"
VALUE_OFF = "off"
VALUE_TOGGLE = "toggle"
