[tool.poetry]
name = "quality-lac-data-ref-authorities"
version = "2021.4-alpha.1"
description = ""
authors = ["Your Name <you@example.com>"]
license = "OGL-UK-3.0"
packages = [
    { include = "qlacref_authorities" },
]

[tool.poetry.dependencies]
python = "^3.7.1"
pandas = "^1.3.4"
pyarrow = "^6.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
