[tool.poetry]
name = "sapiadapter"
version = "0.6.9986"
description = ""
authors = ["Zafar Iqbal <zaf@sparc.space>"]

[tool.poetry.dependencies]
python = "^3.8,<3.11"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
