_comment: Train Dummy model.
augmentation: true
band_ids:
- B01
- B02
- B03
band_means:
  B01: 0.485
  B02: 0.456
  B03: 0.406
band_stds:
  B01: 0.229
  B02: 0.224
  B03: 0.225
batch_size: 2
dataset_dir: Path to your dataset directory this will be used later in train.py and
  dataloader.py to load dataset.
mode: 'epoch'
distributed: false
distributed_val: false
val_frequency: -1
max_iters: 5
gpu: 0
input_shape: 
- 10
- 3
- 256
- 256
local_artifacts_path: Datastore path where dataset should be copied if requried.
loss: binary_jaccard
loss_args:
  jaccard_weight: 0.25
metrics:
- dc
- prec
- recall
model: dummy
nfs_data_path: Datastore path where dataset is.
num_classes: 2
num_gpus: 1
num_workers: 1
optimizer: sgd
optimizer_args:
  lr: 0.1
pretrained_checkpoint: null
project_name: DummyRandomData
resolution: 50
resume_checkpoint: null
scheduler: step
scheduler_args:
  gamma: 0.1
  step_size: 15
sensor: SATELLITE SOURCE NAME FROM WHICH IMAGES IN THE DATASET ARE USED
weight_dir: Path of directory where checkpoints should be saved.