[tool.poetry]
name = "plutto"
version = "0.2.0"
description = "The official Python client for Plutto API"
authors = ["Nicolas Massardo <nmassardot@uc.cl>"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://getplutto.com/"
repository = "https://github.com/plutto-labs/plutto-python"
exclude = [
    ".github",
    ".coveragerc",
    ".flake8",
    ".pylintrc",
    "Makefile",
    "scripts",
    "tests"
]

[tool.poetry.dependencies]
python = "^3.7"
httpx = ">=0.16, < 1.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
isort = "^5.6.4"
pylint = "^2.6.0"
pytest = "^6.1.1"
pytest-cov = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
