[tool.poetry]
name = "termcolor-enum"
version = "1.2.0"
description = "Drop-in [termcolor](https://pypi.org/project/termcolor/) replacement with enums and type hinting"
authors = ["aidan <achaplin3@gatech.edu>"]
readme = 'README.md'
license = 'MIT'
homepage = 'https://gitlab.com/TheBicameralMind/termcolor-enum'


[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
