[tool.poetry]
name = "replies"
version = "0.0.1"
description = "Composable, pure, immutable toolkit for HTTP APIs"
authors = ["Arie Bovenberg <a.c.bovenberg@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
