# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'client_id',
    'secret_key',
]

__config__ = pulumi.Config('frontegg')

client_id = __config__.get('clientId')
"""
The client ID for a Frontegg portal API key.
"""

secret_key = __config__.get('secretKey')
"""
The corresponding secret key for the API key.
"""

