[tool.poetry]
name = "unu_api"
version = "0.2.0"
description = "Библиотека для интеграции с биржой микрозадач unu.im"
authors = ["Egorov Egor"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.910"
black = "^21.11b1"
pylint = "^2.11.1"
bandit = "^1.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
