
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-26T17:21:47-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d70d29a7db0ab34f4e2d1b79db8b4fc5af50ae20",
 "version": "0.4.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
