[tool.poetry]
name = "vault-bitwarden-client"
version = "1.0.0"
description = "Use Bitwarden to unlock Ansible vaults"
authors = ["Philip Douglass <philip@philipdouglass.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
vault-bitwarden-client = "vault_bitwarden_client:main"

[tool.black]
target-version = ["py36", "py37", "py38", "py39"]
