DIRECTION = {
    "BaratDaya": "southwest",
    "BaratLaut": "northwest",
    "Tenggara": "southeast",
    "TimurLaut": "northeast",
    "Utara": "north",
    "Selatan": "south",
    "Timur": "east",
    "Barat": "west"
}

TIMEZONE_OFFSETS = ( "WIB", "WITA", "WIT" )

# WIND_DIRECTION_CODE = {
#     "N": "North",
#     "NNE": "North-Northeast",
#     "NE": "Northeast",
#     "ENE": "East-Northeast",
#     "E": "East",
#     "ESE": "East-Southeast",
#     "SE": "Southeast",
#     "SSE": "South-Southeast",
#     "SSW": "South-Southwest",
#     "SW": "Southwest",
#     "WSW": "West-Southwest",
#     "W": "West",
#     "S": "South",
#     "WNW": "West-Northwest",
#     "NW": "Northwest",
#     "NNW": "North-Northwest",
#     "VARIABLE": "Fluctuate"
# }
# 
# WEATHER_CODE = {
#     "0":   ("Clear Skies", "cerah"),
#     "1":   ("Partly Cloudy", "cerah%20berawan"),
#     "2":   ("Partly Cloudy", "cerah%20berawan"),
#     "3":   ("Mostly Cloudy", "berawan"),
#     "4":   ("Overcast", "berawan%20tebal"),
#     "5":   ("Haze", "udara%20kabur"),
#     "10":  ("Smoke", "asap"),
#     "45":  ("Fog", "kabut"),
#     "60":  ("Light Rain", "hujan%20ringan"),
#     "61":  ("Rain", "hujan%20sedang"),
#     "63":  ("Heavy Rain", "hujan%20lebat"),
#     "80":  ("Isolated Shower", "hujan%20lokal"),
#     "95":  ("Severe Thunderstorm", "hujan%20petir"),
#     "97":  ("Severe Thunderstorm", "hujan%20petir"),
#     "100": ("Clear Skies", "cerah"),
#     "101": ("Partly Cloudy", "cerah%20berawan"),
#     "102": ("Partly Cloudy", "cerah%20berawan"),
#     "103": ("Mostly Cloudy", "berawan"),
#     "104": ("Overcast", "berawan%20tebal")
# }
# 
# PROVINCES = {
#     "aceh": "Aceh",
#     "bali": "Bali",
#     "bangka_belitung": "BangkaBelitung",
#     "banten": "Banten",
#     "bengkulu": "Bengkulu",
#     "dki_yogyakarta": "DIYogyakarta",
#     "dki_jakarta": "DKIJakarta",
#     "gorontalo": "Gorontalo",
#     "jambi": "Jambi",
#     "jawa_barat": "JawaBarat",
#     "jawa_tengah": "JawaTengah",
#     "jawa_Timur": "JawaTimur",
#     "kalimantan_barat": "KalimantanBarat",
#     "kalimantan_selatan": "KalimantanSelatan",
#     "kalimantan_tengah": "KalimantanTengah",
#     "kalimantan_timur": "KalimantanTimur",
#     "kalimantan_utara": "KalimantanUtara",
#     "kepulauan_riau": "KepulauanRiau",
#     "lampung": "Lampung",
#     "maluku": "Maluku",
#     "maluku_utara": "MalukuUtara",
#     "nusa_tenggara_barat": "NusaTenggaraBarat",
#     "nusa_tenggara_timur": "NusaTenggaraTimur",
#     "papua": "Papua",
#     "papua_barat": "PapuaBarat",
#     "riau": "Riau",
#     "sulawesi_barat": "SulawesiBarat",
#     "sulawesi_selatan": "SulawesiSelatan",
#     "sulawesi_sengah": "SulawesiTengah",
#     "sulawesi_tenggara": "SulawesiTenggara",
#     "sulawesi_utara": "SulawesiUtara",
#     "sumatera_barat": "SumateraBarat",
#     "sumatera_selatan": "SumateraSelatan",
#     "sumatera_utara": "SumateraUtara",
#     "indonesia": "Indonesia"
# }