#
# Deploy module-specific configuration (specified in "item") to a device
#
- debug:
    msg: |
      {{ item }} configuration for {{ inventory_hostname }}
      =========================================
      {{ lookup('template','../templates/'+item+'/'+ansible_network_os+'.j2') }}
    verbosity: 1
  tags: [ test,module ]

- include_tasks: "deploy-config/{{ansible_network_os}}.yml"
  tags: [ module ]
  args:
    apply:
      vars:
        config_template: "../templates/{{ item }}/{{ansible_network_os}}.j2"
      tags: [ always ]
