
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-18T15:50:42-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8704c3ecf6632a72c55e012ed117d56f85a21f74",
 "version": "0.13.43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
