
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-24T13:31:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd3b811598c82de055e5a010235018ad8ba2a446",
 "version": "1.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
