# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/tools/hp_util.ipynb (unless otherwise specified).

__all__ = ['print_util']

# Cell
def print_util (x):
    ''' dummy example

    Arguments:
        x: integer
    '''
    print (f'the input is {x}')