
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-24T22:41:51+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ccc781d8054d1a5de801a62aabb8659a228fdcda",
 "version": "3.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
