BASE_URL = "https://theforexapi.com/api/"

CODE_SYMBOL = {
    "AUD": "AU$",
    "BGN": "лв",
    "BRL": "R$",
    "CAD": "C$",
    "CHF": "",
    "CNY": "",
    "CZK": "",
    "DKK": "",
    "EUR": "",
    "GBP": "",
    "HKD": "",
    "HRK": "",
    "HUF": "",
    "IDR": "",
    "INR": "",
    "ISK": "",
    "JPY": "",
    "KRW": "",
    "MXN": "",
    "MYR": "",
    "NOK": "",
    "NZD": "",
    "PHP": "",
    "PLN": "",
    "RON": "",
    "RUB": "",
    "SEK": "",
    "SGD": "",
    "THB": "",
    "TRY": "",
    "USD": "",
    "ZAR": "",
}

CODE_SYMBOL = {
    "AUD": "",
    "BGN": "",
    "BRL": "",
    "CAD": "",
    "CHF": "",
    "CNY": "",
    "CZK": "",
    "DKK": "",
    "EUR": "",
    "GBP": "",
    "HKD": "",
    "HRK": "",
    "HUF": "",
    "IDR": "",
    "INR": "",
    "ISK": "",
    "JPY": "",
    "KRW": "",
    "MXN": "",
    "MYR": "",
    "NOK": "",
    "NZD": "",
    "PHP": "",
    "PLN": "",
    "RON": "",
    "RUB": "",
    "SEK": "",
    "SGD": "",
    "THB": "",
    "TRY": "",
    "USD": "",
    "ZAR": "",
}
