[tool.poetry]
name = "aprofiles"
version = "0.2.0"
description = "Analysis of atmospheric profilers measurements"
authors = ["augustinm <augustinm@met.no>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
matplotlib = "^3.5.0"
miepython = "^2.2.1"
netCDF4 = "^1.5.8"
numpy = "^1.21.4"
seaborn = "^0.11.2"
scipy = "^1.7.2"
tqdm = "^4.62.3"
xarray = "^0.20.1"

[tool.poetry.dev-dependencies]
pydata-sphinx-theme = "^0.7.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
