
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-24T22:36:47+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "c7d678d93e8a41696d581b9390ad2e23de5f73b7",
 "version": "3.7.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
