# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from aim.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from aim.model.application import Application
from aim.model.assembly_diagnostics import AssemblyDiagnostics
from aim.model.assembly_info import AssemblyInfo
from aim.model.assembly_item import AssemblyItem
from aim.model.asset import Asset
from aim.model.asset_create import AssetCreate
from aim.model.asset_segment import AssetSegment
from aim.model.attribute_definition import AttributeDefinition
from aim.model.attribute_definition_create import AttributeDefinitionCreate
from aim.model.attribute_definition_edit import AttributeDefinitionEdit
from aim.model.attribute_definition_entity import AttributeDefinitionEntity
from aim.model.attribute_value import AttributeValue
from aim.model.attribute_value_entity import AttributeValueEntity
from aim.model.cell import Cell
from aim.model.classification_node import ClassificationNode
from aim.model.column_definition import ColumnDefinition
from aim.model.complex_value_base import ComplexValueBase
from aim.model.component import Component
from aim.model.component_create import ComponentCreate
from aim.model.component_edit import ComponentEdit
from aim.model.component_info import ComponentInfo
from aim.model.component_type import ComponentType
from aim.model.component_type_info import ComponentTypeInfo
from aim.model.contact import Contact
from aim.model.contact_entity import ContactEntity
from aim.model.contact_info import ContactInfo
from aim.model.db_update import DbUpdate
from aim.model.document import Document
from aim.model.document_create import DocumentCreate
from aim.model.document_info import DocumentInfo
from aim.model.entity import Entity
from aim.model.entity_base import EntityBase
from aim.model.entity_contact import EntityContact
from aim.model.entity_create import EntityCreate
from aim.model.entity_edit import EntityEdit
from aim.model.entity_mapping_info import EntityMappingInfo
from aim.model.entity_match_descriptor import EntityMatchDescriptor
from aim.model.entity_match_info import EntityMatchInfo
from aim.model.entity_ref import EntityRef
from aim.model.facility import Facility
from aim.model.facility_info import FacilityInfo
from aim.model.file_upload_result import FileUploadResult
from aim.model.footprint import Footprint
from aim.model.i_metered_resource import IMeteredResource
from aim.model.ifc_type import IfcType
from aim.model.inline_object2 import InlineObject2
from aim.model.inline_object3 import InlineObject3
from aim.model.inline_object4 import InlineObject4
from aim.model.inline_object5 import InlineObject5
from aim.model.inline_object6 import InlineObject6
from aim.model.issue import Issue
from aim.model.issue_info import IssueInfo
from aim.model.job import Job
from aim.model.job_create import JobCreate
from aim.model.job_edit import JobEdit
from aim.model.job_info import JobInfo
from aim.model.level import Level
from aim.model.level_create import LevelCreate
from aim.model.level_edit import LevelEdit
from aim.model.level_info import LevelInfo
from aim.model.mapping_message_info import MappingMessageInfo
from aim.model.mapping_properties import MappingProperties
from aim.model.member_permission import MemberPermission
from aim.model.member_role import MemberRole
from aim.model.model import Model
from aim.model.model_create import ModelCreate
from aim.model.model_edit import ModelEdit
from aim.model.model_info import ModelInfo
from aim.model.model_mapping import ModelMapping
from aim.model.model_mapping_report import ModelMappingReport
from aim.model.o_data_list_response_of_application import ODataListResponseOfApplication
from aim.model.o_data_list_response_of_assembly_diagnostics import ODataListResponseOfAssemblyDiagnostics
from aim.model.o_data_list_response_of_assembly_item import ODataListResponseOfAssemblyItem
from aim.model.o_data_list_response_of_asset import ODataListResponseOfAsset
from aim.model.o_data_list_response_of_attribute_definition import ODataListResponseOfAttributeDefinition
from aim.model.o_data_list_response_of_attribute_definition_entity import ODataListResponseOfAttributeDefinitionEntity
from aim.model.o_data_list_response_of_attribute_value import ODataListResponseOfAttributeValue
from aim.model.o_data_list_response_of_complex_value_base import ODataListResponseOfComplexValueBase
from aim.model.o_data_list_response_of_component import ODataListResponseOfComponent
from aim.model.o_data_list_response_of_component_type import ODataListResponseOfComponentType
from aim.model.o_data_list_response_of_contact import ODataListResponseOfContact
from aim.model.o_data_list_response_of_document import ODataListResponseOfDocument
from aim.model.o_data_list_response_of_entity import ODataListResponseOfEntity
from aim.model.o_data_list_response_of_entity_ref import ODataListResponseOfEntityRef
from aim.model.o_data_list_response_of_facility import ODataListResponseOfFacility
from aim.model.o_data_list_response_of_issue import ODataListResponseOfIssue
from aim.model.o_data_list_response_of_job import ODataListResponseOfJob
from aim.model.o_data_list_response_of_level import ODataListResponseOfLevel
from aim.model.o_data_list_response_of_member_permission import ODataListResponseOfMemberPermission
from aim.model.o_data_list_response_of_model import ODataListResponseOfModel
from aim.model.o_data_list_response_of_model_mapping import ODataListResponseOfModelMapping
from aim.model.o_data_list_response_of_model_mapping_report import ODataListResponseOfModelMappingReport
from aim.model.o_data_list_response_of_resource import ODataListResponseOfResource
from aim.model.o_data_list_response_of_role import ODataListResponseOfRole
from aim.model.o_data_list_response_of_row import ODataListResponseOfRow
from aim.model.o_data_list_response_of_schedule import ODataListResponseOfSchedule
from aim.model.o_data_list_response_of_site import ODataListResponseOfSite
from aim.model.o_data_list_response_of_space import ODataListResponseOfSpace
from aim.model.o_data_list_response_of_spare import ODataListResponseOfSpare
from aim.model.o_data_list_response_of_system_item import ODataListResponseOfSystemItem
from aim.model.o_data_list_response_of_zone import ODataListResponseOfZone
from aim.model.o_data_response_of_boolean import ODataResponseOfBoolean
from aim.model.quota_status import QuotaStatus
from aim.model.related_entity import RelatedEntity
from aim.model.resource import Resource
from aim.model.resource_info import ResourceInfo
from aim.model.role import Role
from aim.model.role_member import RoleMember
from aim.model.row import Row
from aim.model.schedule import Schedule
from aim.model.site import Site
from aim.model.space import Space
from aim.model.space_create import SpaceCreate
from aim.model.space_edit import SpaceEdit
from aim.model.space_info import SpaceInfo
from aim.model.spare import Spare
from aim.model.spare_create import SpareCreate
from aim.model.spare_edit import SpareEdit
from aim.model.spare_info import SpareInfo
from aim.model.system_info import SystemInfo
from aim.model.system_item import SystemItem
from aim.model.user_permissions import UserPermissions
from aim.model.value_container import ValueContainer
from aim.model.zone import Zone
from aim.model.zone_info import ZoneInfo
