[tool.poetry]
name = "ptermtools"
version = "0.1.0a0"
description = "Paul's Terminal Tools"
authors = [
    "Paul Gierz <paulgierz@gmail.com>"
]
license = "Apache-2.0"
readme = "README.md"
packages = [
    { include = "ptermtools", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.7"
importlib-metadata = {version = "^4.8.2", python = "<3.8"}
click8 = "^8.0.1"
fs = "^2.4.14"
PyGithub = "^1.55"
python-gitlab = "^2.10.1"
docker = "^5.0.3"
spython = "^0.1.17"
taskw = "^1.3.0"
everett = "^2.0.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.15.0"
tox = "^3.24.4"
pytest = "^6.2.5"

[tool.black]
line-length = 88
target-python = "3.7"

[tool.isort]
profile = "black"
src_paths = ["src", "test"]
known_first_party = "ptermtools"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = [
    "tests",
]

[tool.tox]
legacy_tox_ini = """
[tox]
minversion = 3.13.0
isolated_build = True
envlist = py

[testenv]
whitelist_externals = poetry
setenv =
commands =
    poetry install --no-root
    pytest {posargs}

[testenv:lint]
skip_install = True
deps =
    pre-commit
commands =
    pre-commit run --all-files {posargs}

"""

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
