[tool.poetry]
name = "multidirectorycorpusreader"
version = "0.2.2"
description = ""
authors = ["Michael Andersen <michael10andersen+mdcr@gmail.com>"]
license = "lgpl-3.0"
readme = "README.md"
repository = "https://github.com/blackplague/multidirectorycorpusreader"
packages = [ { include = "multidirectorycorpusreader" } ]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/blackplague/multidirectorycorpusreader/issues"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
flake8 = "^4.0.1"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
