
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-24T01:14:52-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "b6a6ee7ef699dfd3bf4dc8cacb31fa7cc10d680c",
 "version": "1.5.4rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
