version: '3.4'
services:
    zmq_server:
        image: "maxxiking/zmq_server:1.0.3"
        ports:
            - "<port>:<FRONTEND_PORT>"
        environment:
            FROM_CONFIG: 0
            SECURE: 0
            IP: 0.0.0.0
            FRONTEND_PORT: <FRONTEND_PORT>
            BACKEND_PORT: <BACKEND_PORT>
            LOG_DIR: <LOG_DIR>
            LOGGING_MODE: <SERVER_LOG_MODE>
        restart: always
        volumes:
            - <BIND_VOLUME>:/workdir
        networks:
            - view_factor_network

    view_factor_worker:
        image: "maxxiking/shading_worker:1.0.3"
        environment:
            FROM_CONFIG: 0
            IP: zmq_server
            SERVER_PORT: <BACKEND_PORT>
            LOG_DIR: logs
            LOGGING_MODE: <WORKER_LOG_MODE>
        volumes:
            - <BIND_VOLUME>:/workdir
        networks:
            - view_factor_network
        restart: always
        deploy:
            mode: replicated
            replicas: <NUM_WORKERS>

    pyftp:
        image: "maxxiking/pyftp:latest"
        container_name: pyftp
        entrypoint: python main.py
        restart: always
        ports:
            - "<FTP_Port1>:20"
            - "<FTP_Port2>:21"
            - "<FTP_PassivePorts>:7000-7050"
        volumes:
            - <BIND_VOLUME>:/workdir
        environment:
            USER: <UserName>
            PASSWORD: <UserPassword>

networks:
  view_factor_network:
        name: prod_shading_network
        driver: bridge

volumes:
    <BIND_VOLUME>:
      external: true
