[tool.poetry]
name = "mcmahon"
version = "0.3.0"
description = "McMahon Tournament Manager"
authors = ["Oleksandr Hiliazov <oleksandr.hiliazov@eleks.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
scipy = "^1.7.2"

[tool.poetry.dev-dependencies]
Faker = "^9.8.0"
pytest = "^6.2.5"
pre-commit = "^2.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
