"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc

from .remote_pb2 import *
class RemoteExecutorStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    # These 3 are deprecated and will be removed soon
    RemoteCall:grpc.UnaryUnaryMultiCallable[
        global___RemoteCallRequest,
        global___RemoteCallResponse] = ...

    LaunchBlockingJob:grpc.UnaryUnaryMultiCallable[
        global___LaunchBlockingJobRequest,
        global___LaunchBlockingJobResponse] = ...

    PostResult:grpc.UnaryUnaryMultiCallable[
        global___PostResultRequest,
        global___PostResultResponse] = ...

    CreateTask:grpc.UnaryUnaryMultiCallable[
        global___CreateTaskRequest,
        global___CreateTaskResponse] = ...

    WaitForResult:grpc.UnaryUnaryMultiCallable[
        global___WaitForResultRequest,
        global___WaitForResultResponse] = ...

    # Sets the cron jobs associated to an app. If the list of cron jobs is
    # empty, removes all the cron jobs.
    SetCronJobs:grpc.UnaryUnaryMultiCallable[
        global___SetCronJobsRequest,
        global___SetCronJobsResponse] = ...


class RemoteExecutorServicer(metaclass=abc.ABCMeta):
    # These 3 are deprecated and will be removed soon
    @abc.abstractmethod
    def RemoteCall(self,
        request: global___RemoteCallRequest,
        context: grpc.ServicerContext,
    ) -> global___RemoteCallResponse: ...

    @abc.abstractmethod
    def LaunchBlockingJob(self,
        request: global___LaunchBlockingJobRequest,
        context: grpc.ServicerContext,
    ) -> global___LaunchBlockingJobResponse: ...

    @abc.abstractmethod
    def PostResult(self,
        request: global___PostResultRequest,
        context: grpc.ServicerContext,
    ) -> global___PostResultResponse: ...

    @abc.abstractmethod
    def CreateTask(self,
        request: global___CreateTaskRequest,
        context: grpc.ServicerContext,
    ) -> global___CreateTaskResponse: ...

    @abc.abstractmethod
    def WaitForResult(self,
        request: global___WaitForResultRequest,
        context: grpc.ServicerContext,
    ) -> global___WaitForResultResponse: ...

    # Sets the cron jobs associated to an app. If the list of cron jobs is
    # empty, removes all the cron jobs.
    @abc.abstractmethod
    def SetCronJobs(self,
        request: global___SetCronJobsRequest,
        context: grpc.ServicerContext,
    ) -> global___SetCronJobsResponse: ...


def add_RemoteExecutorServicer_to_server(servicer: RemoteExecutorServicer, server: grpc.Server) -> None: ...
