name: Unit tests
on: [pull_request]
jobs:
  run:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python  
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Static code checking with pyflakes
      run: |
        pip3 install pyflakes
        pyflakes skorecard
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel twine
        pip3 install ".[all]"
    - name: Generate coverage report
      run: |
        pytest --cov=src --cov-report=xml
