[tool.poetry]
name = "py-appconfig"
version = "0.1.2"
description = "Persistent configuration storage for python applications"
readme = "README.md"
homepage = "https://github.com/anujdatar/py-appconfig"
authors = ["Anuj Datar <anuj.datar@gmail.com>"]
license = "MIT"
packages = [{include = "appconfig"}]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
