
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-26T16:55:35-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "93403712e9d1a1da87059ed39bbff55e58003d28",
 "version": "2021.11.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
