#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['yaqc_qtpy', 'yaqc_qtpy.property_items']

package_data = \
{'': ['*'], 'yaqc_qtpy': ['splash-images/*']}

install_requires = \
['yaqd-core>=2020.06.3', 'yaqc', 'qtpy', 'qtypes>=0.3.0', 'pyside2']

extras_require = \
{'dev': ['black', 'pre-commit']}

entry_points = \
{'console_scripts': ['yaqc-qtpy = yaqc_qtpy.__main__:main']}

setup(name='yaqc-qtpy',
      version='2021.11.0',
      description='Tooling for building simple yaq clients using qtpy.',
      author='Blaise Thompson',
      author_email='blaise@untzag.com',
      url='https://yaq.fyi',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.7',
     )
