[tool.poetry]
name = "itm_core"
version = "0.1.0"
description = ""
authors = ["Булыгин Евгений Андреевич <ebulygin@ussc.ru>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
