VERSION_YEAR = 2021
VERSION_MONTH = int('11')
VERSION_DAY = int('20')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('59')
MAJOR_VERSION = 1
MINOR_VERSION = 7
PATCH_VERSION = 202111200759
version_date = '2021/11/20 07:59'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
