
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-19T17:48:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a6767f6f2d4469a4eddbcd9aab27bd7b4e1a43d6",
 "version": "0.32.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
