strictness: high
autodetect: true
doc-warnings: true
test-warnings: true
member-warnings: true

pep257:
  run: true
  disable:
    - D210
    - D212
    - D213
    - D413
    - D407
    - D406
    - D203
    - D401

pycodestyle:
  disable:
    - E741

pep8:
  run: true
  disable:
    - E741
    - N815
    - N802
    - N816
    - N806

pylint:
  run: true
  disable:
    - R1729

bandit:
  run: true
  assert_used:
    skips: ['*_test.py', 'test_*.py']


pyroma:
  run: true

pyflakes:
  run: true
  disable:
    - F401


mccabe:
  run: true
  disable:
    - MC0001
