[tool.poetry]
name = "Flunt"
version = "0.1.0"
description = "Python implementation of Domain Notification Pattern based in Flunt (.NET) developed by @andrebaltieri"
authors = ["Emerson Delatorre <38289677+Delatorrea@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
