[tool.poetry]
name = "VectorX"
version = "1.0.0"
description = "class Vector(x=0, y=0, z=0)"
authors = ["semenchuk Community <hootuk@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
