[tool.poetry]
name = "pybookmd"
version = "1.0.8"
description = "\"Simple book building CLI for markdown based books\""
authors = ["Dylan Kirby <dylankirbydev@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
fastcore = "1.3.19"
packaging = "20.9"
pypandoc = "1.5"
pyparsing = "2.4.7"
click = "^8.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
build = "pybookmd.cli:build_book"
