version: 2
formats: all
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  apt_packages:
  - libgirepository1.0-dev
  - gir1.2-poppler-0.18
  - gir1.2-pango-1.0
python:
  install:
  - requirements: docs/requirements.txt
  - path: .
sphinx:
  configuration: docs/conf.py
