
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-21T22:26:29-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "c656aa088cca0fe0e9d822c033641a109a30f494",
 "version": "v1.1.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
