#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['jipdate']

package_data = \
{'': ['*']}

install_requires = \
['jinja2', 'jira', 'PyYAML']

entry_points = \
{'console_scripts': ['jipdate = jipdate.jipdate:main',
                     'jipfp = jipdate.jipfp:main',
                     'jipstatus = jipdate.jipstatus:main']}

setup(name='jipdate',
      version='0.0.1',
      description='Command line tool for Jira',
      author=None,
      author_email='Joakim Bech <joakim.bech@linaro.org>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
