
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-19T08:39:17+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf41d3261f36505229a07a0196f7547b5a908baa",
 "version": "2021.11.0+4.gbf41d32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
