# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(514, 431)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 60, 361, 121))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.getUsers = QtWidgets.QPushButton(self.centralwidget)
        self.getUsers.setGeometry(QtCore.QRect(420, 210, 81, 31))
        self.getUsers.setMaximumSize(QtCore.QSize(81, 31))
        self.getUsers.setObjectName("getUsers")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(30, 210, 371, 121))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.send_message = QtWidgets.QPushButton(self.centralwidget)
        self.send_message.setGeometry(QtCore.QRect(30, 340, 81, 31))
        self.send_message.setObjectName("send_message")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 250, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 290, 81, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.connect_client = QtWidgets.QPushButton(self.centralwidget)
        self.connect_client.setGeometry(QtCore.QRect(410, 10, 81, 31))
        self.connect_client.setObjectName("connect_client")
        self.client_name = QtWidgets.QTextEdit(self.centralwidget)
        self.client_name.setGeometry(QtCore.QRect(80, 10, 91, 31))
        self.client_name.setObjectName("client_name")
        self.client_name_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.client_name_2.setGeometry(QtCore.QRect(280, 10, 111, 31))
        self.client_name_2.setObjectName("client_name_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 51, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 20, 61, 20))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 514, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.getUsers.setText(_translate("MainWindow", "Contacts"))
        self.send_message.setText(_translate("MainWindow", "Send"))
        self.pushButton_2.setText(_translate("MainWindow", "Add client"))
        self.pushButton_3.setText(_translate("MainWindow", "Del client"))
        self.connect_client.setText(_translate("MainWindow", "Connect"))
        self.label_2.setText(_translate("MainWindow", "Login"))
        self.label_3.setText(_translate("MainWindow", "Password"))
