
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-25T21:02:53-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed759a0954ed980af3cb2198c0783427529abe12",
 "version": "2.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
