
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-19T11:29:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "22a06e2e638eb5042e5e147566f69dad53f3b1eb",
 "version": "0.7.1.post.dev168"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
