info = {"message": "Get only task ids via drf-flexfields (DEV-1102) (#1747)", "commit": "cd38b7ae0e432d44dfd0f88b9f976af6e052743c", "date": "2021-11-19 13:01:37 +0300", "branch": "release/1.4", "version": "1.3.0+193.gcd38b7ae.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
