language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"
before_install:
  - sudo apt-get install --no-install-recommends cython libhdf4-dev libhdfeos-dev python-imaging python-numpy python-matplotlib python-mpltoolkits.basemap ttf-bitstream-vera
install:
  - python setup.py install 
script: cd test; ./test.sh
