# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"normalize_conf": "02_core.ipynb",
         "write_dfset": "02_core.ipynb",
         "HECSS_Sampler": "02_core.ipynb",
         "HECSS": "02_core.ipynb",
         "dfset_writer": "03_cli.ipynb",
         "hecss_sampler": "03_cli.ipynb",
         "THz": "04_monitor.ipynb",
         "plot_band_set": "04_monitor.ipynb",
         "plot_bands": "04_monitor.ipynb",
         "plot_bands_file": "04_monitor.ipynb",
         "run_alamode": "04_monitor.ipynb",
         "get_dfset_len": "04_monitor.ipynb",
         "show_dc_conv": "04_monitor.ipynb",
         "build_bnd_lst": "04_monitor.ipynb",
         "build_omega": "04_monitor.ipynb",
         "plot_omega": "04_monitor.ipynb",
         "monitor_phonons": "04_monitor.ipynb",
         "load_dfset": "04_monitor.ipynb",
         "plot_stats": "04_monitor.ipynb",
         "monitor_stats": "04_monitor.ipynb"}

modules = ["core.py",
           "cli.py",
           "monitor.py"]

doc_url = "https://jochym.gitlab.io//hecss/"

git_url = "https://gitlab.com/jochym/hecss"

def custom_doc_links(name): return None
