[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "octopus-sensing"
version = "3.0.2"
description = "Library for recording data synchronously from different physiological sensors"
authors = ["Nastaran Saffaryazdi <nsaffar@gmail.com>", "Aidin Gharibnavaz <aidin@aidinhut.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://octopus-sensing.nastaran-saffar.me"
repository = "https://github.com/nastaran62/octopus-sensing"
keywords = ["sensors", "eeg", "gsr", "recorder"]

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
sounddevice = "^0.4.0"
scipy = "^1.5.2"
opencv-python = "^4.4.0"
# pyOpenBCI doesn't list its dependencies correctly.
# The followings are pyOpenBCI's dependencies.
pyOpenBCI = "^0.13"
pyserial = "^3.4"
requests = "^2.24.0"
xmltodict = "^0.12.0"
# bluepy is not needed by pyOpenBCI on Windows platform (bluepy doesn't support windows)
bluepy = { version = "^1.3.0", markers = "os_name != 'nt'" }
bitstring = "^3.1.7"
# End of pyOpenBCI dependencies.
msgpack = "^1.0.0"
# pyaudio doesn't support windows
pyaudio = { version = "^0.2.11", markers = "os_name != 'nt'" }
pandas = "^1.2.4"
mne = "^0.23.0"
heartpy = "^1.2.7"
pycairo = "^1.20.1"
PyGObject = "3.40.1"
screeninfo = "^0.7"
miniaudio = "^1.45"
brainflow = "^4.6.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.782"
coverage = "^5.2.1"
sphinx = "^4.3.0"
sphinx-rtd-theme = "^1.0.0"


[tool.autopep8]
max_line_length = 100
