[tool.poetry]
name = "negargparse"
version = "0.2.0"
description = ""
authors = ["Sriram Krishna <ksri91@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/k-sriram/negargparse"
repository = "https://github.com/k-sriram/negargparse"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
] # See https://pypi.org/classifiers/

[tool.poetry.dependencies]
python = "^3.7"
typing-extensions = { version = ">= 4.0.0", python = "< 3.8" }

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^6.2.5"                                             # Lowest: see https://github.com/pytest-dev/pytest/pull/8540
flake8 = "^4.0.1"                                             # >=3.7, use of per-file-ignore
black = "^21.11b0"
mypy = "^0.910"
pre-commit = "^2.15.0"
coverage = "^6.1.2"                                           # poetry doesn't detect coverage as a dependency of pytest-cov
pytest-cov = "^3.0.0"
tox = "^3.24.4"
importlib-metadata = { version = ">= 1.4", python = "< 3.8" }

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^6.2.5"
coverage = "^6.1.2"
pytest-cov = "^3.0.0"

[tool.poetry.group.test-mypy]
optional = true

[tool.poetry.group.test-mypy.dependencies]
pytest = "^6.2.5"
mypy = "^0.910"


[build-system]
requires = [
    "poetry-core>=1.2.0a2",
] # Lowest: was having problems with https://github.com/python-poetry/poetry/issues/2855
build-backend = "poetry.core.masonry.api"

[tool.mypy]
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_unused_ignores = true
show_error_codes = true

[[tool.mypy.overrides]]
module = ["tests.*"]
disallow_untyped_defs = false


[tool.pytest.ini_options]
minversion = "6.2.5"
addopts = ["--cov=negargparse"]
xfail_strict = true
testpaths = ["tests"]
python_functions = ["test_*", "example_*", "validate_*"]
markers = ["testvalid: validates tests"]
