
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-24T11:46:21+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e45d00c78496683ca09902f66dd23007db61f355",
 "version": "0.24.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
