
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-25T10:28:29-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b08c11620b76799d63acc6bc282bb15a31624c70",
 "version": "v1.1.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
