
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-26T20:30:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bafe80c0961de8394768a7ea6aef95749d32bdbe",
 "version": "v0.3.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
