def _help_terminator():
    print('≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡ HELP FUNCTION INACTIVE ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡')
    return

def _help_plot_grid():
    print('================ plot_grid() ================')
    print('This function serves the purpose of defining a "grid" for the plot_data() function, which allows for plotting of multiple data sets in however many different plots desired.')
    print('More options below:')
    print('1: Variables')
    print('2: Output')
    print('0: Terminate _help()')
    print('-1: Go back')
    help_id_inner = input('Choose from list: ')
    if help_id_inner == '1': 
        print('-------- Variables --------')
        print('<nr> defines the figure number')
        print('-- Input: numeral values of both integer and non-integer type (integers recommended)')
        print('-- Default: int(0)')
        print()
        print('<r> defines the number of rows of plots in the figure')
        print('-- Input: integers >= 1')
        print('-- Default: int(1)')
        print()
        print('<s> defines the number of columns of plots in the figure')
        print('-- Input: integers')
        print('-- Default: int(1) >= 1')
        print()
        print('<share> defines which axis´ should be shared')
        print('-- Input: if int(1) or string(x), x-axis´ are shared, if int(2) or string(y), y-axis´ are shared, if int(3), string(xy), string(yx) or string(both), xy-axis´ are shared, if int(0) or string(no),  no axis´ are shared')
        print('-- Default: int(0)')
        print()
        print('<set_dpi> sets the dpi of the figure')
        print('--- Input: numerical value greater than 0')
        print('--- Default: int(300)')
        help_terminator = input('Terminate _help(): 0, back to parent: -1: ')
        if help_terminator == '0':
            _help_terminator()
        elif help_terminator == '-1':
            _help_plot_grid()
    elif help_id_inner == '2':
        print('-------- Output --------')
        print('<figure_global_output> (global) defined by matplotlib.pyplot.subplots() figure')
        print('<ax_global_output> (global) defined by matplotlib.pyplot.subplots() axis')
        print('<figure_number_global_output> (global) defined by <nr>')
        print('<share_axis_bool_output> (global) defined by <share>')
        print('<boundary_ax_global_fix> (global) defined as product of <r> and <s>')
        help_terminator = input('Terminate _help(): 0, back to parent: -1: ')
        if help_terminator == '0':
            _help_terminator()
        elif help_terminator == '-1':
            _help_plot_grid()
    elif help_id_inner == '-1':
        _help(1)
    elif help_id_inner == '0':
        _help_terminator()

def _help_plot_data():
    print('================ plot_data() ================')
    print('This function plots input data according to the grid defined by plot_grid(), and can plot multiple data sets in multiple different ways.')
    print('More options below:')
    print('1: Variables')
    print('2: Output')
    print('0: Terminate _help()')
    print('-1: Go back')
    help_id_inner = input('Choose from list: ')
    if help_id_inner == '1': 
        print('-------- Variables --------')
        print('<p> defines the plot indexing number')
        print('-- Input: integers >= 0')
        print('-- Default: int(0)')
        print()
        print('<xs> defines the lists (this variable is a list consisting of lists), thus if only one x-list is the script will try to construct a parent list')
        print('-- Input: if single xs-list, input just that list, if multiple x-lists, input those lists in a list')
        print('-- Default: N/A')
        print()
        print('<ys> defines the lists (this variable is a list consisting of lists), thus if only one y-list is the script will try to construct a parent list')
        print('-- Input: if single y-list, input just that list, if multiple y-lists, input those lists in a list')
        print('-- Default: N/A')
        print()
        print('<ttl> defines the title of the subplots (or figure title if share_ttl=True)')
        print('-- Input: string')
        print('-- Default: None')
        print()
        print('<dlab> defines data-labels')
        print('-- Input: list of strings corresponding to number of plotted data sets (len(xs))')
        print('-- Default: N/A')
        print()
        print('<xlab> defines common x-label for all plots')
        print('--- Input: string')
        print('--- Default: None')
        print()
        print('<ylab> defines common y-label for all plots')
        print('--- Input: string')
        print('--- Default: None')
        print()
        print('<ms> defines marker size if needed')
        print('--- Input: numeral values >= 0')
        print('--- Default: int(1)')
        print()
        print('<lw> defines line width if needed')
        print('--- Input: numeral values >= 0')
        print('--- Default: int(1)')
        print()
        print('<ls> defines line style if needed')
        print('--- Input: list of strings corresponding to number of plotted data sets (len(xs)) according to matplotlib.pyplot´s line styles: https://matplotlib.org/stable/gallery/lines_bars_and_markers/linestyles.html')
        print('--- Default: string(solid)')
        print()
        print('<dcol> data color; defines color of plotted data points or lines')
        print('--- Input: list of color strings corresponding to number of plotted data sets (len(xs)) according to matplotlib.pyplot´s colors: https://matplotlib.org/stable/gallery/color/named_colors.html')
        print('--- Default: string(black)')
        print()
        print('<plt_type> defines the plot type')
        print('--- Input: int(0) or string(plot) plots data as axs[].plot(), int(1) or string(scatter) plots as axs.scatter(), int(3) or string(qqplot) plots a qqplot in axs[], and a axs[+1].boxplot()')
        print('--- Default: int(0)')
        print()
        print('<tight> fixes tight layout according to bool')
        print('--- Input: bool')
        print('--- Default: True')
        print()
        print('<mark> defines marker type of plotted data if needed')
        print('--- Input: list of marker type strings corresponding to number of plotted data sets (len(xs)) according to https://matplotlib.org/stable/api/markers_api.html')
        print('--- Default: string(.)')
        print()
        print('<trsp> determmines the transparency of the data dots or lines (the alpha of the data-plot)')
        print('--- Input: list of numerical values from 0 to 1 corresponding to number of plotted data sets (len(xs))')
        print('--- Default: int(1)')
        print()
        print('<v_ax> defines a preset vertical axis')
        print('--- Input: if None display no axis, if int(0) display solid standard axis line, if int(1) display dashed axis line, if int(2) display dotted axis line')
        print('--- Default: None')
        print()
        print('<h_ax> defines a preset horisontal axis')
        print('--- Input: if None display no axis, if int(0) display solid standard axis line, if int(1) display dashed axis line, if int(2) display dotted axis line')
        print('--- Default: None')
        print()
        print('<no_ticks> determines whether or not axis ticks are visible')
        print('--- Input: if False, then ticks are visible, if True; ticks are not visible')
        print('--- Default: False')
        print()
        print('<share_ttl> determines if the plot titles should be shared as a figure title')
        print('--- Input: bool')
        print('--- Default: False')
        help_terminator = input('Terminate _help(): 0, back to parent: -1: ')
        if help_terminator == '0':
            _help_terminator()
        elif help_terminator == '-1':
            _help_plot_grid()
    elif help_id_inner == '2':
        print('-------- Output --------')
        print('A simple or advanced plot of data with the corresponding inputs, in one or multiple plots')
        help_terminator = input('Terminate _help(): 0, back to parent: -1: ')
        if help_terminator == '0':
            _help_terminator()
        elif help_terminator == '-1':
            _help_plot_grid()
    elif help_id_inner == '-1':
        _help(1)
    elif help_id_inner == '0':
        _help_terminator()

def _help(x=0):
    if x == 0:
        print('≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡ HELP FUNCTION ACTIVE ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡')
    print('1: plot_grid()')
    print('2: plot_data()')
    print('0: Terminate function')
    help_id_outer = input('Choose from list above: ')
    if help_id_outer == '1':
        _help_plot_grid()
        return
    elif help_id_outer == '2':
        _help_plot_data()
        return
    elif help_id_outer == '0':
        _help_terminator()
