[build-system]
requires = ["setuptools>=42.0","wheel","Cython"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=slapping"
testpaths = [
    "tests",
]

[tool.sdist]
include = ["src/text2ipa/__init__.pyi"]

[tool.mypy]
mypy_path = 'stubs'
check_untyped_defs = true
disallow_any_generics = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true